### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserModel'

### ISSUE THREAD

**Issue by DeGenius360** [joicejoseph3198/Flask-Voting-App#1]
https://github.com/joicejoseph3198/Flask-Voting-App/blob/483e0db73a671d62b9b61224612a803a01993cde/app/views.py#L70

Hello Joseph, I got the above error when trying to add a new candidate for the president position. Any idea how I can resolve this?

**Comment by DeGenius360** [comment]
Traceback (most recent call last):
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dg/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dg/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dg/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dg/Projects/Voting2/Flask-Voting-App/app/views.py", line 70, in candidate_post
    if not 10000000 <= int(roll_no) < 99999999:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserModel'

**Comment by joicejoseph3198** [comment]
Sorry I saw your email pretty late. Could you give me a detailed
description and maybe attach some screenshots?
